image: quay.io/vgteam/dind

before_script:
  - whoami
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get -q -y update
  # Make sure we have some curl stuff for pycurl which we need for some Python stuff
  - apt-get -q -y install --no-upgrade docker.io python3-pip python3-virtualenv libcurl4-gnutls-dev python-dev libgnutls28-dev
  # Ubuntu 20.04 doesn't seem to ship singularity, so we install from source
  # https://stackoverflow.com/questions/50537404/error-called-singularity-config-get-value-on-uninitialized-config-subsystem-wh
  - apt-get -q -y install wget libarchive-dev squashfs-tools
  - wget https://github.com/singularityware/singularity/releases/download/2.6.1/singularity-2.6.1.tar.gz
  - tar xf singularity-2.6.1.tar.gz
  - pushd singularity-2.6.1
  - ./configure --prefix=/usr/local > /dev/null
  - make > /dev/null
  - make install > /dev/null
  - popd
  - rm -rf singularity-2.6.1.tar.gz singularity-2.6.1 
  # TODO: Make Singularity use the Docker cache with a wrapper like Toil will.
  # Configure Docker to use a mirror for Docker Hub and restart the daemon
  # Set the registry as insecure because it is probably cluster-internal over plain HTTP.
  - |
    if [[ ! -z "${DOCKER_HUB_MIRROR}" ]] ; then
        echo "{\"registry-mirrors\": [\"${DOCKER_HUB_MIRROR}\"], \"insecure-registries\": [\"${DOCKER_HUB_MIRROR##*://}\"]}" | sudo tee /etc/docker/daemon.json
    fi
  - startdocker || true
  - docker info
  # Build .pypirc with PyPI credentials
  - touch ~/.pypirc
  - chmod 600 ~/.pypirc
  - 'printf "[distutils]\nindex-servers =\n    pypi\n\n[pypi]\nusername: ${PYPI_USERNAME}\npassword: ${PYPI_PASSWORD}\n" > ~/.pypirc'

after_script:
  - stopdocker || true

stages:
  - test

test-job:
  stage: test
  script:
    - ./ci.sh 
  artifacts:
    # Let Gitlab see the junit report
    reports:
      junit: test-report.xml
    when: always
  
